modLoader="javafml"
loaderVersion="[36,)"
issueTrackerURL="https://github.com/Flaxbeard/ImmersivePetroleum/issues"
license="All rights reserved"

[[mods]] #mandatory
	modId="immersivepetroleum"
	version="${version}"
	displayName="Immersive Petroleum"
	displayURL="https://minecraft.curseforge.com/projects/immersive-petroleum"
	authors="Flaxbeard"
	description="Adds oil and oil processing features to Immersive Engineering."
	logoFile="logo.png"
	#updateJSONURL=""
	#credits=""

[[dependencies.immersivepetroleum]]
	modId="immersiveengineering"
	mandatory=true
	versionRange="[1.16.5-5.0.0,)"
	ordering="BEFORE"
	side="BOTH"

[[dependencies.immersivepetroleum]]
	modId="forge"
	mandatory=true
	versionRange="[36.1.0,)"
	ordering="NONE"
	side="BOTH"

[[dependencies.immersivepetroleum]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.16.5]"
	ordering="NONE"
	side="BOTH"
